### ISSUE TITLE
unsafeHead

### ISSUE THREAD

**Issue by andrewthad** [haskell-hvr/text-short#14]
An `unsafeHead :: ShortText -> Char` function in `Data.Text.Short.Unsafe` would be useful in a situation I'm in. Would you take a PR for this?

**Comment by hvr** [comment]
@andrewthad what's wrong with https://hackage.haskell.org/package/text-short-0.1.3/docs/Data-Text-Short-Partial.html#v:head ? :-)

**Comment by andrewthad** [comment]
I don't recall what I originally needed this for, but `head` is probably fine, and I suspect that GHC will optimize away the length check if I've guarded on the length elsewhere. I'll reopen this if I realize that GHC does not optimize this in certain situations.
