### ISSUE TITLE
Release a version compatible with GHC 9.10

### ISSUE THREAD

**Issue by Qqwy** [haskell-hvr/text-short#45]
I was about to open a PR to fix some outdated documentation, when I found out while reading the source code that #36 which was merged ~10 months ago had done just that.

When will a new version with the updated documentation be released to Hackage?

**Comment by phadej** [comment]
Most likely GHC-9.10 (i.e. `foldl'` in `Prelude` will force the release: https://github.com/haskell-hvr/text-short/pull/43).

**Comment by andreasabel** [comment]
And so the time has come...

**Comment by andreasabel** [comment]
Indeed, we have the build error with GHC 9.10:
```
src/Data/Text/Short/Internal.hs:69:7: error: [GHC-87543]
    Ambiguous occurrence ‘foldl'’.
    It could refer to
       either ‘Prelude.foldl'’,
              imported from ‘Prelude’ at src/Data/Text/Short/Internal.hs:(139,1)-(144,80)
              (and originally defined in ‘ghc-internal-9.1001.0:GHC.Internal.Data.Foldable’),
           or ‘Data.Text.Short.Internal.foldl'’,
              defined at src/Data/Text/Short/Internal.hs:586:1.
   |
69 |     , foldl'
   |       ^^^^^^
```

**Comment by angerman** [comment]
@phadej can we cut a release? With GHC 9.10 being effectively in the wild now, this necessitates usage of head.hackage, and has head.hackage leak out of GHC development. I don't think we want anyone ever to depend on head.hackage but GHC developers.

**Comment by phadej** [comment]
I won't make a release until GHC-9.10.1 is out. If you are using alphas, deal with problems caused.

**Comment by andreasabel** [comment]
Making it easier for more developers to evaluate the alpha and RC versions of GHC will in the end benefit GHC development (and the whole Haskell ecosystem as a whole), as more regressions can be caught in time by more pre-release testing.  
Frankly, I don't see what is gained by postponing the release here.

**Comment by phadej** [comment]
> It happens often enough that you then need to make another change for the final release

The `head.hackage` patch is good enough, use it.

**Comment by hasufell** [comment]
> > It happens often enough that you then need to make another change for the final release
> 
> The `head.hackage` patch is there to be used

Here you're forgetting a small detail: the end user has no easy way of knowing which patch in `head.hackage` is upstream approved and which one is just cooked up by random contributors who don't really know the codebases.

That does make a pretty significant difference.

**Comment by andreasabel** [comment]
If you also have to work around this ... here is a snippet for the `cabal.project.local`:
```
source-repository-package
  type:     git
  location: https://github.com/haskell-hvr/text-short
  tag:      9c4c133afc0b0d284e9c61477dcb9a20862f49f8
```

**Comment by nomeata** [comment]
Very timely, thanks a lot! With this and
```
index-state: 2024-04-28T06:04:17Z
with-compiler: ghc-9.10.0.20240426
allow-newer:
  candid:*,
  *:base,
  *:template-haskell,
  *:deepseq,
  *:bytestring,
  *:text,
  *:ghc,
  *:containers

source-repository-package
  type:     git
  location: https://github.com/haskell-hvr/text-short
  tag:      9c4c133afc0b0d284e9c61477dcb9a20862f49f8
```
I could confirm that my package is 9.10.1-ready.

**Comment by tomjaguarpaw** [comment]
> Most likely GHC-9.10 (i.e. foldl' in Prelude will force the release: https://github.com/haskell-hvr/text-short/pull/43).

We now have GHC-9.10, so could the release please be made?

**Comment by tchoutri** [comment]
@phadej It would be really kind of you to push a release.

**Comment by Bodigrim** [comment]
`text-short` is the last package which needs an upgrade for one of my products to migrate to GHC 9.10 (everything else works fine with `--allow-newer` only). It would be great to have a release soon.

(GHC 9.10 and Cabal 3.12 are quite a game-changer because of semaphore builds and multiple home units, so I'm keen to upgrade asap)

**Comment by tchoutri** [comment]
@phadej also I'd be happy to give a hand regarding bounds bumps and compat PRs, if you are overworked. :)

**Comment by tomjaguarpaw** [comment]
I'm also willing to volunteer for bounds-bumping assistance.

**Comment by phadej** [comment]
Blocked on https://github.com/haskell/ghcup-metadata/pull/210 (or actually on GHC-9.10 available in the default release channel of ghcup).

Having multiple pings over the weekend won't make me do anything any faster.

**Comment by phadej** [comment]
The bump bumping is something I don't need help with. The release management overall is something I wouldn't trust many people to do.

**Comment by hasufell** [comment]
> Blocked on [haskell/ghcup-metadata#210](https://github.com/haskell/ghcup-metadata/pull/210) (or actually on GHC-9.10.1 being available in the default release channel of ghcup).
> 

Yeah, it's weekend and I'm eating my chocolate cake.

**Comment by hasufell** [comment]
https://github.com/haskell/ghcup-metadata/pull/211

**Comment by phadej** [comment]
https://hackage.haskell.org/package/text-short-0.1.6

**Comment by Bodigrim** [comment]
It seems to say `base >=4.12 && <4.20`, no?
